### PR TITLE
Fix for #7: Random is now thread safe

### PR DESCRIPTION
**Pull request by ebbz**
Updated the random class to use a new random object for each seperate thread.

Had problems running a single unit tests due to a localization issue. Made a fix on that one as well.

### CODE REVIEW

**Comment by ebbz** [comment]
I signed it!

**Comment by SergeyKanzhelev** [comment]
Why not use Guid? Global lock seems to be less optimal

**Comment by ebbz** [comment]
When using Random() you insert the array with a size of bytes you want the random bytes for. When using Guid() you get 16 bytes. Which are unqiue, but not really random. When using a part of the guid things might not be as random as you think (https://blogs.msdn.microsoft.com/oldnewthing/20080627-00/?p=21823).

I will do an update on the global locking. Since each thread has its own _local. I don't think you need any synchronisation.

**Comment by lmolkova** [comment]
@ebbz the article you are referring to is from 2008 and at that time guid were not random indeed. 
According to our tests now, guids are pretty randomly distributed and we are relying on them for sampling decisions.

**Comment by SergeyKanzhelev** [comment]
I'm OK with this implementation. GUID's goal is to generate unique value. We need random. So if lock is eliminated - lets move on. If benchmarking will show better results using guid in future we can always change.

**Pull request merged**
